version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    ports: ["4566:4566"]
    environment:
      - SERVICES=dynamodb
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DEBUG=1

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  notification-service:
    build:
      context: .
      dockerfile: DockerfileDev.notification   # runs the app module (dev)
    ports: ["8083:8083"]
    environment:
      SPRING_PROFILES_ACTIVE: dev

      # Mail (to MailHog)
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"

      # Notification provider + links
      NOTIFY_PROVIDER: smtp
      NOTIFICATION_FROM: no-reply@phshoes.local
      NOTIFICATION_BASE-URL: http://localhost:3000

      # Token codec
      VERIFICATION_TOKEN_SECRET: dev-dev-dev
      VERIFICATION_TOKEN_TTL_SECONDS: "900"

      # DynamoDB (LocalStack)
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: ap-southeast-1
      AWS_DYNAMODB_REGION: ap-southeast-1
      AWS_DYNAMODB_TABLE: NotificationStore
      AWS_DYNAMODB_ENDPOINT: http://localstack:4566
      AWS_DYNAMODB_LOCALSTACK-ENABLED: "true"
    depends_on:
      - localstack
      - mailhog
